server:
  port: 8188

spring:
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /**
  mail:
    host: smtp.qq.com  # 配置 smtp 服务器地址
    port: 465  # smtp 服务器端口 默认25（阿里云不支持25）
    username:  #配置你的邮箱地址
    password:  #配置申请到的授权码
    protocol: smtp #协议
    comment-reminder-template: mail  #设置要解析发送的html模板（需要你将mail.html文件放到/resources/templates下面）
    friend-link-apply-template: mail-friendlink-apply  #友链申请提醒邮件模板
    friend-link-pass-template: mail-friendlink-pass  #友链申请成功邮件模板
    friend-link-reject-template: mail-friendlink-reject  #友链申请失败邮件模板

    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: com.chenzhen.blog.entity

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

#默认封面路径
default-cover-path: /images/default_cover.jpg