logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wan1324520
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    hikari:
      max-lifetime: 120000

upload:
  directory:
    file: D:\cz-blog-upload\file\
    music: D:\cz-blog-upload\